page=('..........<a href="www.facebook.com">facebook</a>.........')
print(page)
start_link=(page.find('<a href'))
print(start_link)
start_quote=(page.find('"',start_link))
print(start_quote)
end_quote=(page.find('"',start_quote + 1))
print(end_quote)
url=(page[start_quote + 1:end_quote])
print(url)
